# Generated by Django 4.2 on 2023-04-28 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('generation', models.IntegerField()),
                ('body', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField()),
                ('start_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('bid', models.IntegerField(default=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]))),
                ('is_active', models.BooleanField(default=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='axaxa.availablecarlist')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
