# Generated by Django 4.2 on 2023-04-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_id',
        ),
        migrations.AddField(
            model_name='cars',
            name='body',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='brand',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='generation',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='model',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
