# Generated by Django 4.2 on 2023-04-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0002_remove_cars_car_id_cars_body_cars_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='bid',
            field=models.IntegerField(null=True),
        ),
    ]
