# Generated by Django 4.2 on 2023-04-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0003_alter_cars_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='user_id',
            new_name='user',
        ),
    ]
