# Generated by Django 4.2 on 2023-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0004_rename_user_id_cars_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='generation',
            field=models.CharField(max_length=10),
        ),
    ]
