# Generated by Django 4.2 on 2023-05-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0005_alter_cars_generation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=False, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
