# Generated by Django 4.2 on 2023-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axaxa', '0006_alter_cars_options_cars_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
