# Generated by Django 4.2 on 2023-06-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('axaxa', '0009_alter_cars_options_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='cars',
            name='bid_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cars',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='lots', to=settings.AUTH_USER_MODEL),
        ),
    ]
